language: bash

before_install:
        - sudo apt-get update && sudo apt-get install -y shellcheck
        - sudo apt-get install imagemagick
        - wget "https://c4pr1c3.gitee.io/linuxsysadmin/exp/chap0x04/worldcupplayerinfo.tsv"
        - wget "https://c4pr1c3.gitee.io/linuxsysadmin/exp/chap0x04/web_log.tsv.7z"
        - sudo apt-get install p7zip-full
        - 7z x -ot web_log.tsv.7z

script:
        - echo "task 1------------"
        - shellcheck task1.sh
        - bash task1.sh -c
        - bash task1.sh -q
        - bash task1.sh -s
        - bash task1.sh -a
        - bash task1.sh-r
        - echo "task 2------------"
        - shellcheck task2.sh
        - bash task2.sh -h
        - bash task2.sh -a
        - bash task2.sh -b
        - bash task2.sh -c
        - bash task2.sh -d
        - echo "task 3------------"
        - shellcheck task3.sh
        - bash task3.sh  -h
        - bash task3.sh -a
        - bash task3.sh  -b
        - bash task3.sh  -c
        - bash task3.sh  -d
        - bash task3.sh  -e
        - bash task3.sh  -f 

notifications:
  email:
    on_success: never
